var tbl = [
    {
      job_title: "Junior Watson Front End Developer",
      job_url: "https://jobs3.netmedia1.com/cp/faces/job_summary?job_id=SWG-0658825",
      job_id: "SWG-0658825",
      job_description: "IBM Watson Group creates products and technologies using Cognitive Computing to solve real problems, from winning Jeopardy or assisting cancer doctors. Watson does this by analyzing massive amounts of structured and unstructured data. We are on the cutting edge of technology working to change the world.<br><br>Our team within Watson Group works on Watson Explorer, a web application enabling data exploration and visualization. We are looking for senior and junior front-end developers to join us.<br><br><strong>How we work:</strong><br><ul><li>Open and collaborative office environment - you will not be stuffed into a cubicle and left alone</li><li>Software craftsmanship - pairing, Test Driven Development (TDD), small commits in Git, Gerrit code reviews, continuous integration and deployment, daily standups with progress visualization</li><li>Technologies we use - CSS (Sass and Compass), JS, JRuby on Rails, and Java</li></ul><strong>What you'll do:</strong><ul><li>Develop full-stack web applications, our team is application focused not just User Interface (UI) focused</li><li>Work with designers and researchers to translate users’ needs into reality</li><li>Influence design and direction of product</li></ul><strong>Requirements:</strong><ul><li>6 months - 1 year experience in software development preferably with any or all of the technologies we use</li><li>English: Fluent</li></ul>Want to come work with us? We're interested in you, too! Let us know why you'd be a great fit for our team and product."
    },{
      job_title: "Senior Watson Front End Developer",
      job_url: "https://jobs3.netmedia1.com/cp/faces/job_summary?job_id=SWG-0658818",
      job_id: "SWG-0658818",
      job_description: "IBM Watson Group creates products and technologies using Cognitive Computing to solve real problems, from winning Jeopardy or assisting cancer doctors. Watson does this by analyzing massive amounts of structured and unstructured data. We are on the cutting edge of technology working to change the world.<br><br>Our team within Watson Group works on Watson Explorer, a web application enabling data exploration and visualization. We are looking for senior and junior front-end developers to join us.<br><br><strong>How we work:</strong><ul><li>Open and collaborative office environment - you will not be stuffed into a cubicle and left alone.</li><li>Software craftsmanship - pairing, Test Driven Development (TDD), small commits in Git, Gerrit code reviews, continuous integration and deployment, daily standups with progress visualization</li><li>Technologies we use - CSS (Sass and Compass), JS, JRuby on Rails, and Java</li></ul><strong>What you'll do:</strong><ul><li>Develop full-stack web applications, our team is application focused not just User Interface (UI) focused</li><li>Work with designers and researchers to translate users’ needs into reality</li><li>Influence design and direction of product</li></ul><strong>Requirements:</strong><ul><li>3 years experience in software development preferably with any or all of the technologies we use</li><li>English: Fluent</li></ul>Want to come work with us? We're interested in you, too! Let us know why you'd be a great fit for our team and product."
    },{
      job_title: "Junior Watson UX Designer",
      job_url: "https://jobs3.netmedia1.com/cp/faces/job_summary?job_id=SWG-0636275",
      job_id: "SWG-0636275",
      job_description: "IBM Watson uses Cognitive Computing to solve hard problems (like winning Jeopardy) using massive amounts of structured and unstructured data. This position is about creating and designing the next generation of data exploration and visualization cognitive products.<br><br>Looking for an experienced User Experience (UX) and interaction designer who has an eye for clean and intuitive design to help shape the next generation of large-scale web and cloud based applications. Candidate will be passionate about creating the best possible experience for the users and have the ability to work as part of a cross-functional team in a driven highly collaborative environment.<br><br>Candidate will demonstrate reserves of leadership and technical curiosity and tenacity and be skilled in team collaboration and leadership. Familiarity with Lean UX and integrating with agile development practices.<br><br><strong>Candidate job responsibilities include:</strong><ul><li>Work with Product Management and users to understand both market and user needs and help define visual strategies for enterprise web and mobile business applications and products. This includes planning and conducting user research.</li><li>Work with Product Management (PM) and the rest of the team to articulate and apply a variety of design methodologies to develop concepts and the necessary design and UX artifacts to implement the product vision.</li><li>Create wireframes, User Interface (UI) layouts, mockups, prototypes, visual artifacts, icons and design specifications that are ready to be implemented by the rest of the team.</li><li>Own the design of the product from concept phase to implementation and be able to defend it using research and design principle arguments to other stakeholders.</li><li>Candidate will have a record of delivering awesome designs into web, application and/or products (including mobile first).</li></ul>Interested in learning more about IBM Watson?  <a href='http://www.ibm.com/smarterplanet/us/en/ibmwatson/'' target='_blank'>Check this out.</a><br><br><strong>Required:</strong><ul><li>Bachelor's Degree</li><li>At least 1 year experience in Web, application and product design</li><li>At least 1 year experience in Mobile design</li><li>English: Fluent</li></ul><strong>Preferred:</strong><ul><li>At least 1 years experience in CSS</li><li>At least 1 year experience in JavaScript</li></ul>"
    },{
      job_title: "Experienced Watson UX Designer",
      job_url: "https://jobs3.netmedia1.com/cp/faces/job_summary?job_id=SWG-0636262",
      job_id: "SWG-0636262",
      job_description: "IBM Watson uses Cognitive Computing to solve hard problems (like winning Jeopardy) using massive amounts of structured and unstructured data. This position is about creating and designing the next generation of data exploration and visualization cognitive products.<br><br>Looking for an experienced User Experience (UX) and interaction designer who has an eye for clean and intuitive design to help shape the next generation of large-scale web and cloud based applications. Candidate will be passionate about creating the best possible experience for the users and have the ability to work as part of a cross-functional team in a driven highly collaborative environment.<br><br>Candidate will demonstrate reserves of leadership and technical curiosity and tenacity and be skilled in team collaboration and leadership. Familiarity with Lean UX and integrating with agile development practices.<br><br><strong>Candidate job responsibilities include:</strong><ul><li>Work with Product Management and users to understand both market and user needs and help define visual strategies for enterprise web and mobile business applications and products. This includes planning and conducting user research.</li><li>Work with Product Management (PM) and the rest of the team to articulate and apply a variety of design methodologies to develop concepts and the necessary design and UX artifacts to implement the product vision.</li><li>Create wireframes, User Interface (UI) layouts, mockups, prototypes, visual artifacts, icons and design specifications that are ready to be implemented by the rest of the team.</li><li>Own the design of the product from concept phase to implementation and be able to defend it using research and design principle arguments to other stakeholders.</li><li>Candidate will have a record of delivering awesome designs into web, application and/or products (including mobile first).</li></ul>Interested in learning more about IBM Watson? <a href='http://www.ibm.com/smarterplanet/us/en/ibmwatson/'' target='_blank'>Check this out.</a><br><br><strong>Required:</strong><ul><li>Bachelor's Degree</li><li>At least 3 years experience in Web, application and product design</li><li>At least 1 year experience in Mobile design</li><li>English: Fluent</li></ul><strong>Preferred:</strong><ul><li>At least 2 years experience in CSS</li><li>At least 3 years experience in JavaScript</li></ul>"
    }
  ]
